### ISSUE TITLE
Parse error URGENT HELP

### ISSUE THREAD

**Issue by ItsGamingTube** [mahtab2003/PROJECT-HUSTAL#22]
Parse error: syntax error, unexpected '<' in /home/vol2_6/website.com/www/client.website.com/htdocs/clientarea/function/signup.php on line 28

Help pls

**Comment by mahtab2003** [comment]
Did you change any code

**Comment by ItsGamingTube** [comment]
Nope.

**Comment by ImLoadingUuU** [comment]
I think you has change the code, line 28 is ?>
or your hustal have some bug in that version

**Comment by gautamjethe** [comment]
@ItsGamingTube can i help you ?
